apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-springboot-deployment
  labels:
    app: hello-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-springboot
  template:
    metadata:
      labels:
        app: hello-springboot
    spec:
      containers:
      - name: hello-springboot
        image: rsxyz123/hello-springboot
        ports:
        - containerPort: 8090

--- 

apiVersion: v1
kind: Service
metadata:
  name: hello-springboot-svc
  labels:
    app: hello-springboot
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8090
    protocol: TCP
    targetPort: 8090
    nodePort: 30190
  selector:
    app: hello-springboot

